name: Build

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/build.yml
      - Makefile
      - pyoxidizer.bzl
      - static/**
      - vendor/**

jobs:
  Linux:
    runs-on: ubuntu-18.04
    container: cr.amira.io/gi0baro/pyoxidizer/gnu:0.23.0

    steps:
    - uses: actions/checkout@v2
    - name: Get build version
      id: build_version
      run: |
        echo ::set-output name=version::$(echo ${GITHUB_SHA} | cut -c1-8)
    - name: Build release
      run: |
        make build_linux
        make pack_linux BUILD_VERSION=${{ steps.build_version.outputs.version }}
    - name: Upload release file
      uses: actions/upload-artifact@v1
      with:
        name: poetry-bin-${{ steps.build_version.outputs.version }}-x86_64-unknown-linux-gnu.tar.gz
        path: dist/poetry-bin-${{ steps.build_version.outputs.version }}-x86_64-unknown-linux-gnu.tar.gz
    - name: Upload checksum file
      uses: actions/upload-artifact@v1
      with:
        name: poetry-bin-${{ steps.build_version.outputs.version }}-x86_64-unknown-linux-gnu.sha256sum
        path: dist/poetry-bin-${{ steps.build_version.outputs.version }}-x86_64-unknown-linux-gnu.sha256sum

  MacOS:
    runs-on: macos-11

    env:
      PYOXIDIZER_SYSTEM_RUST: "1"

    steps:
    - uses: actions/checkout@v2
    - name: Get build version
      id: build_version
      run: |
        echo ::set-output name=version::$(echo ${GITHUB_SHA} | cut -c1-8)
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: "1.65"
        default: true
        profile: minimal
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install PyOxidizer
      run: |
        pip install pyoxidizer==0.23.0
    - name: Build x86_64 release
      run: |
        make build_mac ARCH=x86_64-apple-darwin
        make verify_build_mac ARCH=x86_64-apple-darwin
        make pack_mac ARCH=x86_64-apple-darwin BUILD_VERSION=${{ steps.build_version.outputs.version }}
    # - name: Build aarch64 release
    #   run: |
    #     make build_mac ARCH=aarch64-apple-darwin
    #     make pack_mac ARCH=aarch64-apple-darwin BUILD_VERSION=${{ steps.build_version.outputs.version }}
    - name: Upload x86_64 release file
      uses: actions/upload-artifact@v1
      with:
        name: poetry-bin-${{ steps.build_version.outputs.version }}-x86_64-apple-darwin.tar.gz
        path: dist/poetry-bin-${{ steps.build_version.outputs.version }}-x86_64-apple-darwin.tar.gz
    - name: Upload x86_64 checksum file
      uses: actions/upload-artifact@v1
      with:
        name: poetry-bin-${{ steps.build_version.outputs.version }}-x86_64-apple-darwin.sha256sum
        path: dist/poetry-bin-${{ steps.build_version.outputs.version }}-x86_64-apple-darwin.sha256sum
    # - name: Upload aarch64 release file
    #   uses: actions/upload-artifact@v1
    #   with:
    #     name: poetry-bin-${{ steps.build_version.outputs.version }}-aarch64-apple-darwin.tar.gz
    #     path: dist/poetry-bin-${{ steps.build_version.outputs.version }}-aarch64-apple-darwin.tar.gz
    # - name: Upload aarch64 checksum file
    #   uses: actions/upload-artifact@v1
    #   with:
    #     name: poetry-bin-${{ steps.build_version.outputs.version }}-aarch64-apple-darwin.sha256sum
    #     path: dist/poetry-bin-${{ steps.build_version.outputs.version }}-aarch64-apple-darwin.sha256sum


  Windows:
    runs-on: windows-2019

    env:
      PYOXIDIZER_SYSTEM_RUST: "1"

    steps:
    - uses: actions/checkout@v2
    - name: Get build version
      id: build_version
      shell: bash
      run: |
        echo ::set-output name=version::$(echo ${GITHUB_SHA} | cut -c1-8)
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: "1.65"
        default: true
        profile: minimal
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install PyOxidizer
      run: |
        pip install pyoxidizer==0.23.0
    - name: Build x86_64 release
      shell: bash
      run: |
        make build_win
        make verify_build_win
        make pack_win BUILD_VERSION=${{ steps.build_version.outputs.version }}
    - name: Upload x86_64 release file
      uses: actions/upload-artifact@v1
      with:
        name: poetry-bin-${{ steps.build_version.outputs.version }}-x86_64-pc-windows-msvc.tar.gz
        path: dist/poetry-bin-${{ steps.build_version.outputs.version }}-x86_64-pc-windows-msvc.tar.gz
    - name: Upload x86_64 checksum file
      uses: actions/upload-artifact@v1
      with:
        name: poetry-bin-${{ steps.build_version.outputs.version }}-x86_64-pc-windows-msvc.sha256sum
        path: dist/poetry-bin-${{ steps.build_version.outputs.version }}-x86_64-pc-windows-msvc.sha256sum
