name: Build

on:
  push:
    branches:
      - master

jobs:
  Linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get build version
      id: build_version
      run: |
        echo ::set-output name=version::$(echo ${GITHUB_SHA} | cut -c1-8)
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.47.0
        default: true
        profile: minimal
    - name: Install pyOxidizer
      run: |
        cargo install --git https://github.com/gi0baro/PyOxidizer.git --rev 1d074e3 pyoxidizer
    - name: Building release
      run: |
        make build_linux
        build/x86_64-unknown-linux-gnu/release/install/bin/poetry --version
        make pack_linux BUILD_VERSION=${{ steps.build_version.outputs.version }}
    - name: Upload release file
      uses: actions/upload-artifact@v1
      with:
        name: poetry-bin-${{ steps.build_version.outputs.version }}-x86_64-unknown-linux-gnu.tar.gz
        path: dist/poetry-bin-${{ steps.build_version.outputs.version }}-x86_64-unknown-linux-gnu.tar.gz
    - name: Upload checksum file
      uses: actions/upload-artifact@v1
      with:
        name: poetry-bin-${{ steps.build_version.outputs.version }}-x86_64-unknown-linux-gnu.sha256sum
        path: dist/poetry-bin-${{ steps.build_version.outputs.version }}-x86_64-unknown-linux-gnu.sha256sum

  MacOS:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get build version
      id: build_version
      run: |
        echo ::set-output name=version::$(echo ${GITHUB_SHA} | cut -c1-8)
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.47.0
        default: true
        profile: minimal
    - name: Install pyOxidizer
      run: |
        cargo install --git https://github.com/gi0baro/PyOxidizer.git --rev 1d074e3 pyoxidizer
    - name: Building release
      run: |
        make build_mac
        build/x86_64-apple-darwin/release/install/bin/poetry --version
        make pack_mac BUILD_VERSION=${{ steps.build_version.outputs.version }}
    - name: Upload release file
      uses: actions/upload-artifact@v1
      with:
        name: poetry-bin-${{ steps.build_version.outputs.version }}-x86_64-apple-darwin.tar.gz
        path: dist/poetry-bin-${{ steps.build_version.outputs.version }}-x86_64-apple-darwin.tar.gz
    - name: Upload checksum file
      uses: actions/upload-artifact@v1
      with:
        name: poetry-bin-${{ steps.build_version.outputs.version }}-x86_64-apple-darwin.sha256sum
        path: dist/poetry-bin-${{ steps.build_version.outputs.version }}-x86_64-apple-darwin.sha256sum
