name: Build

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/build.yml
      - pyoxidizer.bzl
      - static/**
      - vendor/**

jobs:
  Linux:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Get build version
      id: build_version
      run: |
        echo ::set-output name=version::$(echo ${GITHUB_SHA} | cut -c1-8)
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.51.0
        default: true
        profile: minimal
    - name: Install PyOxidizer
      run: |
        cargo install pyoxidizer --version 0.11.0
    - name: Build release
      run: |
        make build_linux
        build/x86_64-unknown-linux-gnu/release/install/bin/poetry --version
        make pack_linux BUILD_VERSION=${{ steps.build_version.outputs.version }}
    - name: Upload release file
      uses: actions/upload-artifact@v1
      with:
        name: poetry-bin-${{ steps.build_version.outputs.version }}-x86_64-unknown-linux-gnu.tar.gz
        path: dist/poetry-bin-${{ steps.build_version.outputs.version }}-x86_64-unknown-linux-gnu.tar.gz
    - name: Upload checksum file
      uses: actions/upload-artifact@v1
      with:
        name: poetry-bin-${{ steps.build_version.outputs.version }}-x86_64-unknown-linux-gnu.sha256sum
        path: dist/poetry-bin-${{ steps.build_version.outputs.version }}-x86_64-unknown-linux-gnu.sha256sum

  MacOS:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
    - name: Get build version
      id: build_version
      run: |
        echo ::set-output name=version::$(echo ${GITHUB_SHA} | cut -c1-8)
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.51.0
        default: true
        profile: minimal
    - name: Install PyOxidizer
      run: |
        cargo install pyoxidizer --version 0.11.0
    - name: Build x86_64 release
      run: |
        make build_mac ARCH=x86_64-apple-darwin
        build/x86_64-apple-darwin/release/install/bin/poetry --version
        make pack_mac ARCH=x86_64-apple-darwin BUILD_VERSION=${{ steps.build_version.outputs.version }}
    - name: Upload x86_64 release file
      uses: actions/upload-artifact@v1
      with:
        name: poetry-bin-${{ steps.build_version.outputs.version }}-x86_64-apple-darwin.tar.gz
        path: dist/poetry-bin-${{ steps.build_version.outputs.version }}-x86_64-apple-darwin.tar.gz
    - name: Upload x86_64 checksum file
      uses: actions/upload-artifact@v1
      with:
        name: poetry-bin-${{ steps.build_version.outputs.version }}-x86_64-apple-darwin.sha256sum
        path: dist/poetry-bin-${{ steps.build_version.outputs.version }}-x86_64-apple-darwin.sha256sum
