name: Release

on:
  push:
    tags:
      - '*.*.*-*'

jobs:
  Linux:
    runs-on: ubuntu-latest
    container: ghcr.io/gi0baro/pyoxidizer:0.24.0-gnu

    steps:
      - uses: actions/checkout@v2
      - name: Get build version
        id: build_version
        run: |
          echo ::set-output name=version::${GITHUB_REF#refs/tags/}
      - name: Build release
        run: |
          make build_linux
          make pack_linux BUILD_VERSION=${{ steps.build_version.outputs.version }}
      - name: Upload release file
        uses: actions/upload-artifact@v1
        with:
          name: poetry-bin-${{ steps.build_version.outputs.version }}-x86_64-unknown-linux-gnu.tar.gz
          path: dist/poetry-bin-${{ steps.build_version.outputs.version }}-x86_64-unknown-linux-gnu.tar.gz
      - name: Upload checksum file
        uses: actions/upload-artifact@v1
        with:
          name: poetry-bin-${{ steps.build_version.outputs.version }}-x86_64-unknown-linux-gnu.sha256sum
          path: dist/poetry-bin-${{ steps.build_version.outputs.version }}-x86_64-unknown-linux-gnu.sha256sum

  MacOS:
    runs-on: macos-11

    env:
      PYOXIDIZER_SYSTEM_RUST: "1"

    steps:
      - uses: actions/checkout@v2
      - name: Get build version
        id: build_version
        run: |
          echo ::set-output name=version::${GITHUB_REF#refs/tags/}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: "1.66"
          default: true
          profile: minimal
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install PyOxidizer
        run: |
          pip install pyoxidizer==0.24.0
      - name: Build x86_64 release
        run: |
          make build_mac ARCH=x86_64-apple-darwin
          make pack_mac ARCH=x86_64-apple-darwin BUILD_VERSION=${{ steps.build_version.outputs.version }}
      - name: Upload x86_64 release file
        uses: actions/upload-artifact@v1
        with:
          name: poetry-bin-${{ steps.build_version.outputs.version }}-x86_64-apple-darwin.tar.gz
          path: dist/poetry-bin-${{ steps.build_version.outputs.version }}-x86_64-apple-darwin.tar.gz
      - name: Upload x86_64 checksum file
        uses: actions/upload-artifact@v1
        with:
          name: poetry-bin-${{ steps.build_version.outputs.version }}-x86_64-apple-darwin.sha256sum
          path: dist/poetry-bin-${{ steps.build_version.outputs.version }}-x86_64-apple-darwin.sha256sum

  Windows:
    runs-on: windows-2019

    env:
      PYOXIDIZER_SYSTEM_RUST: "1"

    steps:
    - uses: actions/checkout@v2
    - name: Get build version
      id: build_version
      shell: bash
      run: |
        echo ::set-output name=version::${GITHUB_REF#refs/tags/}
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: "1.66"
        default: true
        profile: minimal
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install PyOxidizer
      run: |
        pip install pyoxidizer==0.24.0
    - name: Build release
      run: |
        make build_win
        make pack_win BUILD_VERSION=${{ steps.build_version.outputs.version }}
    - name: Upload release file
      uses: actions/upload-artifact@v1
      with:
        name: poetry-bin-${{ steps.build_version.outputs.version }}-x86_64-pc-windows-msvc.tar.gz
        path: dist/poetry-bin-${{ steps.build_version.outputs.version }}-x86_64-pc-windows-msvc.tar.gz
    - name: Upload checksum file
      uses: actions/upload-artifact@v1
      with:
        name: poetry-bin-${{ steps.build_version.outputs.version }}-x86_64-pc-windows-msvc.sha256sum
        path: dist/poetry-bin-${{ steps.build_version.outputs.version }}-x86_64-pc-windows-msvc.sha256sum

  Release:
    needs: [Linux, MacOS, Windows]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get tag
        id: tag
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
      - name: Download Linux release file
        uses: actions/download-artifact@master
        with:
          name: poetry-bin-${{ steps.tag.outputs.tag }}-x86_64-unknown-linux-gnu.tar.gz
          path: dist/
      - name: Download Linux checksum file
        uses: actions/download-artifact@master
        with:
          name: poetry-bin-${{ steps.tag.outputs.tag }}-x86_64-unknown-linux-gnu.sha256sum
          path: dist/
      - name: Download MacOS release file
        uses: actions/download-artifact@master
        with:
          name: poetry-bin-${{ steps.tag.outputs.tag }}-x86_64-apple-darwin.tar.gz
          path: dist/
      - name: Download MacOS checksum file
        uses: actions/download-artifact@master
        with:
          name: poetry-bin-${{ steps.tag.outputs.tag }}-x86_64-apple-darwin.sha256sum
          path: dist/
      - name: Download Windows release file
        uses: actions/download-artifact@master
        with:
          name: poetry-bin-${{ steps.tag.outputs.tag }}-x86_64-pc-windows-msvc.tar.gz
          path: dist/
      - name: Download Windows checksum file
        uses: actions/download-artifact@master
        with:
          name: poetry-bin-${{ steps.tag.outputs.tag }}-x86_64-pc-windows-msvc.sha256sum
          path: dist/
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          release_name: ${{ steps.tag.outputs.tag }}
          draft: false
          prerelease: false
      - name: Upload Linux release file asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/poetry-bin-${{ steps.tag.outputs.tag }}-x86_64-unknown-linux-gnu.tar.gz
          asset_name: poetry-bin-${{ steps.tag.outputs.tag }}-x86_64-unknown-linux-gnu.tar.gz
          asset_content_type: application/gzip
      - name: Upload Linux checksum file asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/poetry-bin-${{ steps.tag.outputs.tag }}-x86_64-unknown-linux-gnu.sha256sum
          asset_name: poetry-bin-${{ steps.tag.outputs.tag }}-x86_64-unknown-linux-gnu.sha256sum
          asset_content_type: text/plain
      - name: Upload MacOS release file asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/poetry-bin-${{ steps.tag.outputs.tag }}-x86_64-apple-darwin.tar.gz
          asset_name: poetry-bin-${{ steps.tag.outputs.tag }}-x86_64-apple-darwin.tar.gz
          asset_content_type: application/gzip
      - name: Upload MacOS checksum file asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/poetry-bin-${{ steps.tag.outputs.tag }}-x86_64-apple-darwin.sha256sum
          asset_name: poetry-bin-${{ steps.tag.outputs.tag }}-x86_64-apple-darwin.sha256sum
          asset_content_type: text/plain
      - name: Upload Windows release file asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/poetry-bin-${{ steps.tag.outputs.tag }}-x86_64-pc-windows-msvc.tar.gz
          asset_name: poetry-bin-${{ steps.tag.outputs.tag }}-x86_64-pc-windows-msvc.tar.gz
          asset_content_type: application/gzip
      - name: Upload Windows checksum file asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/poetry-bin-${{ steps.tag.outputs.tag }}-x86_64-pc-windows-msvc.sha256sum
          asset_name: poetry-bin-${{ steps.tag.outputs.tag }}-x86_64-pc-windows-msvc.sha256sum
          asset_content_type: text/plain
